# Generated by Django 5.0.8 on 2024-08-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(help_text="Name of the source", max_length=100),
        ),
    ]
