# Generated by Django 5.0.8 on 2024-08-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0002_accesskey_alter_source_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="access_key",
            field=models.ForeignKey(
                blank=True,
                help_text="Access key for the source if required it will be injected either in headers or query params",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collectors.accesskey",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="headers",
            field=models.JSONField(
                blank=True,
                help_text="Use [KEY_NAME] to inject access key value",
                null=True,
            ),
        ),
    ]
