# Generated by Django 5.0.8 on 2024-08-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0003_source_access_key_alter_source_headers"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the group", max_length=100),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        related_name="source_groups", to="collectors.source"
                    ),
                ),
            ],
        ),
    ]
