# Generated by Django 5.0.8 on 2024-08-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0004_sourcegroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="storage_slug",
            field=models.CharField(
                default="d",
                help_text="Slug of the storage to prefix the data with",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
