# Generated by Django 5.0.8 on 2024-08-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0005_source_storage_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourcegroup",
            name="sources",
        ),
        migrations.AddField(
            model_name="source",
            name="group",
            field=models.ForeignKey(
                help_text="Group of the source",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collectors.sourcegroup",
            ),
        ),
    ]
