# Generated by Django 5.0.8 on 2024-08-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0006_remove_sourcegroup_sources_source_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcegroup",
            name="storage_slug",
            field=models.CharField(
                default=" ",
                help_text="Slug of the storage to prefix the data with (format: lowercase, hyphens)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="source",
            name="storage_slug",
            field=models.CharField(
                help_text="Slug of the storage to prefix the data with (format: lowercase, hyphens)",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("storage_slug", "group"), name="unique_name_group"
            ),
        ),
    ]
