# Generated by Django 5.0.8 on 2024-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collectors",
            "0007_sourcegroup_storage_slug_alter_source_storage_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
