# Generated by Django 5.0.8 on 2024-08-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0010_source_periodicity_source_periodicity_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
