# Generated by Django 5.0.8 on 2024-08-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0012_remove_source_periodicity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="crontab",
        ),
        migrations.AddField(
            model_name="source",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("S", "Secondly"),
                    ("T", "Minutely"),
                    ("H", "Hourly"),
                    ("D", "Daily"),
                    ("W", "Weekly"),
                    ("M", "Monthly"),
                    ("Y", "Yearly"),
                ],
                default="T",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="periodicity_value",
            field=models.IntegerField(
                default=1,
                help_text="Value of periodicity, for example 5 for every 5 minutes in case of minutely periodicity",
            ),
        ),
    ]
