# Generated by Django 5.0.8 on 2024-08-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0013_remove_source_crontab_source_periodicity_and_more"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="periodicity",
        ),
        migrations.RemoveField(
            model_name="source",
            name="periodicity_value",
        ),
        migrations.AddField(
            model_name="source",
            name="interval_schedule",
            field=models.ForeignKey(
                help_text="Celery interval schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.intervalschedule",
            ),
        ),
    ]
