# Generated by Django 5.0.8 on 2024-08-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0016_rename_storage_storageinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="extension",
            field=models.CharField(
                default="json",
                help_text="File extension to save the data with (json, csv, etc.)",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
