# Generated by Django 5.0.8 on 2024-08-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0018_source_paginated_source_pagination_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceHeaders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the header", max_length=100),
                ),
                ("headers", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="source",
            name="headers",
        ),
        migrations.AddField(
            model_name="source",
            name="source_headers",
            field=models.ForeignKey(
                blank=True,
                help_text="Headers to send with the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="collectors.sourceheaders",
            ),
        ),
    ]
