# Generated by Django 5.0.8 on 2024-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0019_sourceheaders_remove_source_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='name',
            field=models.CharField(default=' ', help_text='Name of the access key', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
