# Generated by Django 5.0.8 on 2024-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectors', '0020_accesskey_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='extension',
            field=models.CharField(default='json', help_text='File extension to save the data with (json, csv, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
